modules:
  categories:
    name: Category
    model: KepplerProductsCategory
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]

  products:
    name: Product
    model: KepplerProductsProduct
    actions: [
      'index', 'create', 'update', 'destroy', 'download', 'upload', 'clone'
    ]
