menu:
  keppler_publicity:
    name: Publicity
    current: ['/admin/publicity/ads']
    url_path: /admin/publicity/ads
    icon: rocket
    model: KepplerPublicity::Ad
    # submenu:
    #   - ad:
    #       name: ads
    #       url_path: /admin/publicity/ads
    #       icon: layers
    #       current: ['/admin/publicity/ads']
    #       model: KepplerPublicity::Ad

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User