menu:
  keppler_banners:
    name: Keppler Banners
    current: ['/admin/banners/banners']
    url_path: /admin/banners/banners
    icon: rocket
    model: KepplerBanners::Banner
    # submenu:
    #   - banner:
    #       name: banners
    #       url_path: /admin/banners/banners
    #       icon: layers
    #       current: ['/admin/banners/banners']
    #       model: KepplerBanners::Banner

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User